# Use root/example user/password credentials
version: '3.1'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 81:80
    volumes:
      - ./src:/var/www/html/

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./src:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: a123123a
      MYSQL_DATABASE: myweb
      MYSQL_USER: zero
      MYSQL_PASSWORD: a123123a
